'use client'
import { useEffect, useState } from 'react'
import { useSession } from 'next-auth/react'
import Link from 'next/link'

type SourceDetail = {
  id: string
  slug: string
  label: string
  category: string
  sheetTab: string | null
  ingestionStrategy: string | null
  enabled: boolean
  adapter: string | null
  config: any
  profile: any
  healthStatus: string | null
  consecutiveFailures: number
  lastRunAt: string | null
  lastRunStatus: string | null
  lastRunError: string | null
  totalSeen: number
  totalApproved: number
  totalRejected: number
  createdAt: string
}

const HEALTH_META: Record<string, { label: string, dot: string, pillClass: string }> = {
  working:    { label: 'Working',    dot: '🟢', pillClass: 'bg-green-100 text-green-800' },
  partial:    { label: 'Partiel',    dot: '🟠', pillClass: 'bg-orange-100 text-orange-800' },
  broken:     { label: 'Cassée',     dot: '🔴', pillClass: 'bg-red-100 text-red-800' },
  unverified: { label: 'Non vérifiée', dot: '⚪', pillClass: 'bg-stone-100 text-stone-600' },
  disabled:   { label: 'Désactivée', dot: '⚫', pillClass: 'bg-stone-200 text-stone-500' },
}

type Analytics = {
  slug: string
  label: string
  summary: { total: number; pending: number; approved: number; rejected: number; auto_rejected: number; duplicate: number }
  last30Days: { total: number; pending: number; approved: number; rejected: number; auto_rejected: number; duplicate: number }
  approvalRate: number | null
  avgListingsPerRun: number | null
  daily: Array<{ date: string; count: number }>
  recentRuns: Array<{
    startedAt: string
    status: 'ok' | 'error' | 'skipped'
    listingsFound: number
    listingsNew: number
    imported: number
    duplicates: number
    errors: number
    durationMs: number
    errorMessage?: string
  }>
}

// fixHistory holds three kinds of entries:
//   1. legacy manual notes ({ date, author, note }) — added by hand from this page
//   2. high_error_rate — auto-recorded by the runner when ≥40% of extractions fail
//   3. ai_suggestion — proposal generated by the Tier 2 AI suggester
// Status field tracks open/applied/dismissed for the auto-generated kinds.
type FixHistoryEntry = {
  date: string
  author?: string
  note?: string
  kind?: 'high_error_rate' | 'ai_suggestion'
  status?: 'open' | 'applied' | 'dismissed'
  // high_error_rate
  errorRate?: number
  errorsCount?: number
  attemptedCount?: number
  sampleFailures?: { url: string; reason: string }[]
  // ai_suggestion
  diagnosis?: string
  proposedAction?: 'update_config' | 'change_url' | 'disable' | 'no_change'
  proposedConfig?: Record<string, any> | null
  proposedUrl?: string | null
  reasoning?: string
  confidence?: 'low' | 'medium' | 'high'
  triggeredBy?: { kind: string; date: string }
  reviewedBy?: string
  reviewedAt?: string
}

type Profile = {
  notes?: string
  expectedMinListings?: number | null
  fixHistory?: FixHistoryEntry[]
}

function fmtDate(s: string | null | undefined): string {
  if (!s) return '—'
  return new Date(s).toLocaleString('fr-FR', { dateStyle: 'short', timeStyle: 'short' })
}

function timeAgo(dateStr: string | null): string {
  if (!dateStr) return '—'
  const diff = Date.now() - new Date(dateStr).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 1) return "à l'instant"
  if (mins < 60) return `${mins} min`
  const hours = Math.floor(mins / 60)
  if (hours < 24) return `${hours} h`
  return `${Math.floor(hours / 24)} j`
}

export default function SourceDetailPage({ params }: { params: { slug: string } }) {
  const { data: session } = useSession()
  const slug = params.slug
  const [source, setSource] = useState<SourceDetail | null>(null)
  const [analytics, setAnalytics] = useState<Analytics | null>(null)
  const [loading, setLoading] = useState(true)
  const [notFound, setNotFound] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Profile editing state — local copy synced to backend on blur/save.
  const [notes, setNotes] = useState('')
  const [expectedMin, setExpectedMin] = useState<string>('')
  const [savingProfile, setSavingProfile] = useState(false)
  const [profileMsg, setProfileMsg] = useState<string | null>(null)

  // Fix-history add form
  const [newFixNote, setNewFixNote] = useState('')
  const [addingFix, setAddingFix] = useState(false)

  async function load() {
    setLoading(true)
    setError(null)
    try {
      const [srcRes, anRes] = await Promise.all([
        fetch(`/api/admin/sources`).then(r => r.ok ? r.json() : null),
        fetch(`/api/admin/sources/${encodeURIComponent(slug)}/analytics`),
      ])
      if (Array.isArray(srcRes)) {
        const found = srcRes.find((s: SourceDetail) => s.slug === slug)
        if (!found) {
          setNotFound(true)
          return
        }
        setSource(found)
        const profile = (found.profile as Profile) || {}
        setNotes(profile.notes || '')
        setExpectedMin(profile.expectedMinListings != null ? String(profile.expectedMinListings) : '')
      }
      if (anRes.ok) {
        setAnalytics(await anRes.json())
      } else if (anRes.status === 404) {
        setNotFound(true)
      } else {
        setError(`Analytics: HTTP ${anRes.status}`)
      }
    } catch (e: any) {
      setError(e?.message || 'Erreur réseau')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    load()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slug])

  async function saveProfile(nextProfile: Profile) {
    setSavingProfile(true)
    setProfileMsg(null)
    try {
      const res = await fetch(`/api/admin/sources/${encodeURIComponent(slug)}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ profile: nextProfile }),
      })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        setProfileMsg(`✗ ${data?.error || `HTTP ${res.status}`}`)
        return
      }
      const updated = await res.json() as SourceDetail
      setSource(updated)
      setProfileMsg('✓ Enregistré')
      setTimeout(() => setProfileMsg(null), 2000)
    } catch (e: any) {
      setProfileMsg(`✗ ${e?.message || 'Erreur réseau'}`)
    } finally {
      setSavingProfile(false)
    }
  }

  async function saveNotesAndExpected() {
    const profile: Profile = (source?.profile as Profile) || {}
    const next: Profile = {
      ...profile,
      notes: notes,
      expectedMinListings: expectedMin.trim() === '' ? null : Number(expectedMin),
    }
    await saveProfile(next)
  }

  async function addFixNote() {
    if (!newFixNote.trim()) return
    setAddingFix(true)
    const profile: Profile = (source?.profile as Profile) || {}
    const entry: FixHistoryEntry = {
      date: new Date().toISOString().slice(0, 10),
      author: (session?.user as any)?.email || 'admin',
      note: newFixNote.trim(),
    }
    const next: Profile = {
      ...profile,
      fixHistory: [entry, ...(profile.fixHistory || [])],
    }
    await saveProfile(next)
    setNewFixNote('')
    setAddingFix(false)
  }

  // Tier 2: kick off the AI suggester for the latest open diagnostic. The
  // server-side route reads the diagnostic, fetches sample HTML, calls Claude,
  // and appends the suggestion as a new fixHistory entry — we just refetch.
  const [aiBusy, setAiBusy] = useState(false)
  const [aiMsg, setAiMsg] = useState<string | null>(null)
  async function requestAISuggestion() {
    setAiBusy(true)
    setAiMsg(null)
    try {
      const res = await fetch(`/api/admin/sources/${slug}/ai-suggest`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) {
        setAiMsg(`✗ ${data?.error || 'Erreur'}`)
      } else {
        setAiMsg('✓ Suggestion générée')
        await load()
      }
    } catch (e: any) {
      setAiMsg(`✗ ${e?.message || 'Erreur réseau'}`)
    } finally {
      setAiBusy(false)
      setTimeout(() => setAiMsg(null), 4000)
    }
  }

  async function fixHistoryAction(index: number, action: 'apply' | 'dismiss') {
    setAiBusy(true)
    try {
      const res = await fetch(`/api/admin/sources/${slug}/fix-history-action`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ index, action }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) {
        alert(data?.error || `Erreur ${res.status}`)
      } else {
        await load()
      }
    } catch (e: any) {
      alert(e?.message || 'Erreur réseau')
    } finally {
      setAiBusy(false)
    }
  }

  async function runNow() {
    try {
      const res = await fetch('/api/admin/sources/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ slugs: [slug] }),
      })
      if (!res.ok) {
        const d = await res.json().catch(() => ({}))
        alert(d?.error || `Erreur ${res.status}`)
      }
    } catch (e: any) {
      alert(e?.message || 'Erreur réseau')
    }
  }

  // Verify state — shows the latest verification result inline.
  const [verifyResult, setVerifyResult] = useState<{
    ok: boolean
    listingsFound?: number
    healthStatus?: string
    durationMs?: number
    message?: string
    sampleTitles?: string[]
  } | null>(null)
  const [verifying, setVerifying] = useState(false)

  async function verifyNow() {
    setVerifying(true)
    setVerifyResult(null)
    try {
      const res = await fetch(`/api/admin/sources/${encodeURIComponent(slug)}/verify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      })
      const data = await res.json().catch(() => ({}))
      setVerifyResult(data)
      // Refresh the source row so the header health pill reflects the new state.
      load()
    } catch (e: any) {
      setVerifyResult({ ok: false, message: e?.message || 'Erreur réseau' })
    } finally {
      setVerifying(false)
    }
  }

  if (!session || (session.user as any)?.role !== 'admin') {
    return <div className="px-4 sm:px-5 lg:px-7 py-5"><p className="text-stone-500">Non autorisé</p></div>
  }

  if (loading) return <div className="px-4 sm:px-5 lg:px-7 py-12 text-center text-stone-500">Chargement…</div>
  if (notFound) return (
    <div className="px-4 sm:px-5 lg:px-7 py-12 text-center">
      <p className="text-stone-500 mb-3">Source introuvable.</p>
      <Link href="/admin/sources" className="text-purple-700 hover:underline text-sm">← Retour aux sources</Link>
    </div>
  )
  if (error || !source || !analytics) return (
    <div className="px-4 sm:px-5 lg:px-7 py-12 text-center">
      <p className="text-red-600 mb-3">Erreur: {error || 'données manquantes'}</p>
      <Link href="/admin/sources" className="text-purple-700 hover:underline text-sm">← Retour aux sources</Link>
    </div>
  )

  const profile = (source.profile as Profile) || {}
  const fixHistory = profile.fixHistory || []
  const maxDaily = Math.max(1, ...analytics.daily.map(d => d.count))
  const expectedMinNum = profile.expectedMinListings
  const lastRun = analytics.recentRuns[0]
  const driftWarning = expectedMinNum != null && lastRun && lastRun.status === 'ok' && lastRun.listingsFound < expectedMinNum

  return (
    <div className="px-4 sm:px-5 lg:px-7 py-5 pb-24 lg:pb-10 max-w-5xl">
      <Link href="/admin/sources" className="text-xs text-stone-500 hover:text-stone-900 mb-2 inline-block">← Retour aux sources</Link>

      {/* Header */}
      <div className="mb-5 flex flex-wrap items-start gap-3">
        <div className="flex-1 min-w-0">
          <h1 className="text-xl sm:text-2xl font-extrabold text-stone-900 break-words">{source.label}</h1>
          <div className="flex flex-wrap gap-1.5 items-center text-[11px] mt-1.5">
            <span className="font-mono text-stone-500">{source.slug}</span>
            {source.healthStatus && HEALTH_META[source.healthStatus] && (() => {
              const m = HEALTH_META[source.healthStatus]
              return (
                <span className={`px-2 py-0.5 rounded-full font-bold ${m.pillClass}`}>
                  {m.dot} Santé: {m.label}
                  {source.consecutiveFailures > 0 && ` (${source.consecutiveFailures} échecs consécutifs)`}
                </span>
              )
            })()}
            {source.enabled
              ? <span className="px-2 py-0.5 rounded-full bg-green-50 text-green-700 font-semibold">actif</span>
              : <span className="px-2 py-0.5 rounded-full bg-stone-200 text-stone-600 font-semibold">désactivé</span>}
            {source.adapter && <span className="px-2 py-0.5 rounded bg-stone-100 text-stone-700 font-mono">{source.adapter}</span>}
            {source.ingestionStrategy && <span className="px-2 py-0.5 rounded bg-purple-100 text-purple-800 font-semibold">{source.ingestionStrategy}</span>}
            {source.sheetTab && <span className="px-2 py-0.5 rounded bg-amber-50 text-amber-800">tab: {source.sheetTab}</span>}
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          {source.adapter && (
            <>
              <button
                onClick={verifyNow}
                disabled={verifying}
                className="px-3 py-1.5 rounded-md text-xs font-bold bg-emerald-100 hover:bg-emerald-200 text-emerald-800 transition disabled:opacity-50"
                title="Lance discover() seulement (pas d'extract Claude). Met à jour healthStatus."
              >
                {verifying ? 'Vérification…' : '✓ Vérifier'}
              </button>
              <button
                onClick={runNow}
                className="px-3 py-1.5 rounded-md text-xs font-bold bg-purple-700 hover:bg-purple-800 text-white transition"
              >
                ▶ Run maintenant
              </button>
            </>
          )}
          <Link
            href="/admin/sources"
            className="px-3 py-1.5 rounded-md text-xs font-bold bg-stone-100 hover:bg-stone-200 text-stone-700 transition"
          >
            ✏ Modifier (depuis la table)
          </Link>
        </div>
      </div>

      {/* Verify result inline panel */}
      {verifyResult && (
        <div className={`mb-4 p-3 rounded-lg border text-xs ${
          verifyResult.ok && verifyResult.healthStatus === 'working' ? 'bg-emerald-50 border-emerald-300 text-emerald-900' :
          verifyResult.healthStatus === 'partial' ? 'bg-amber-50 border-amber-300 text-amber-900' :
          'bg-red-50 border-red-300 text-red-900'
        }`}>
          <div className="font-bold mb-1">
            {verifyResult.ok && verifyResult.healthStatus === 'working' && '✓ Vérification réussie'}
            {verifyResult.healthStatus === 'partial' && '⚠ Vérification partielle'}
            {!verifyResult.ok && '✗ Vérification échouée'}
            {verifyResult.durationMs != null && <span className="ml-2 font-normal opacity-70">({Math.round(verifyResult.durationMs)}ms)</span>}
          </div>
          <div>{verifyResult.message}</div>
          {verifyResult.sampleTitles && verifyResult.sampleTitles.length > 0 && (
            <div className="mt-2 text-[11px]">
              Échantillon : {verifyResult.sampleTitles.map((t, i) => <span key={i} className="inline-block bg-white border border-current rounded px-1.5 py-0.5 mr-1 mt-1">{t.slice(0, 60)}</span>)}
            </div>
          )}
        </div>
      )}

      {/* Drift warning */}
      {driftWarning && (
        <div className="mb-4 p-3 rounded-lg bg-amber-50 border border-amber-300 text-amber-900 text-xs">
          <span className="font-bold">⚠ Drift détecté.</span> Le dernier run a trouvé <span className="font-mono">{lastRun.listingsFound}</span> annonces,
          mais le profile attend au moins <span className="font-mono">{expectedMinNum}</span>. Le sélecteur a peut-être changé sur le site source.
        </div>
      )}

      {/* Stats card */}
      <div className="mb-4 grid grid-cols-2 sm:grid-cols-4 gap-3">
        <StatCard label="Importées (30j)" value={analytics.last30Days.total} />
        <StatCard label="Approuvées (30j)" value={analytics.last30Days.approved} className="text-green-700" />
        <StatCard
          label="Taux d'approbation"
          value={analytics.approvalRate != null ? `${Math.round(analytics.approvalRate * 100)}%` : '—'}
        />
        <StatCard
          label="Annonces moy. / run"
          value={analytics.avgListingsPerRun != null ? analytics.avgListingsPerRun : '—'}
        />
      </div>

      {/* Daily histogram */}
      <div className="mb-5 p-3 bg-white border border-stone-200 rounded-lg">
        <div className="text-xs font-bold text-stone-700 mb-2">Imports — 14 derniers jours</div>
        <div className="flex items-end gap-0.5 h-16">
          {analytics.daily.map((d) => {
            const pct = (d.count / maxDaily) * 100
            return (
              <div
                key={d.date}
                title={`${d.date}: ${d.count} importées`}
                className="flex-1 bg-purple-100 hover:bg-purple-200 rounded-t transition"
                style={{ height: `${Math.max(2, pct)}%`, minHeight: '2px' }}
              />
            )
          })}
        </div>
        <div className="flex justify-between text-[9px] text-stone-400 mt-1 font-mono">
          <span>{analytics.daily[0]?.date}</span>
          <span>{analytics.daily[analytics.daily.length - 1]?.date}</span>
        </div>
      </div>

      {/* Recent runs */}
      <div className="mb-5">
        <h2 className="text-sm font-bold text-stone-900 mb-2">10 derniers runs</h2>
        {analytics.recentRuns.length === 0 ? (
          <div className="p-3 bg-stone-50 border border-stone-200 rounded-lg text-xs text-stone-500">
            Aucun run enregistré pour cette source.
          </div>
        ) : (
          <div className="overflow-x-auto bg-white border border-stone-200 rounded-lg">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-stone-200 text-[11px]">
                  <th className="text-left px-3 py-2 font-semibold text-stone-700">Quand</th>
                  <th className="text-center px-3 py-2 font-semibold text-stone-700">Statut</th>
                  <th className="text-right px-3 py-2 font-semibold text-stone-700">Vues</th>
                  <th className="text-right px-3 py-2 font-semibold text-stone-700">Nouvelles</th>
                  <th className="text-right px-3 py-2 font-semibold text-stone-700">Importées</th>
                  <th className="text-right px-3 py-2 font-semibold text-stone-700">Erreurs</th>
                  <th className="text-right px-3 py-2 font-semibold text-stone-700">Durée</th>
                  <th className="text-left px-3 py-2 font-semibold text-stone-700">Erreur</th>
                </tr>
              </thead>
              <tbody>
                {analytics.recentRuns.map((r, i) => (
                  <tr key={i} className="border-b border-stone-100">
                    <td className="px-3 py-1.5 text-stone-700">{timeAgo(r.startedAt)}</td>
                    <td className="px-3 py-1.5 text-center">
                      <span className={r.status === 'ok' ? 'text-green-700' : 'text-red-600'}>
                        {r.status === 'ok' ? '✓' : '✗'} {r.status}
                      </span>
                    </td>
                    <td className="px-3 py-1.5 text-right tabular-nums">{r.listingsFound}</td>
                    <td className="px-3 py-1.5 text-right tabular-nums text-blue-700">{r.listingsNew}</td>
                    <td className="px-3 py-1.5 text-right tabular-nums text-green-700">{r.imported}</td>
                    <td className="px-3 py-1.5 text-right tabular-nums text-red-600">{r.errors}</td>
                    <td className="px-3 py-1.5 text-right tabular-nums text-stone-500">{Math.round(r.durationMs / 1000)}s</td>
                    <td className="px-3 py-1.5 text-red-600 max-w-md truncate">{r.errorMessage}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Profile */}
      <div className="mb-5 p-4 bg-stone-50 border border-stone-200 rounded-lg">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-bold text-stone-900">📝 Profile</h2>
          {profileMsg && <span className="text-[11px] text-stone-600">{profileMsg}</span>}
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
          <label className="space-y-1 text-xs sm:col-span-2">
            <span className="block font-semibold text-stone-700">Notes admin</span>
            <textarea
              value={notes}
              onChange={e => setNotes(e.target.value)}
              onBlur={saveNotesAndExpected}
              rows={4}
              placeholder="Quirks, sélecteurs custom, contacts internes, anything à savoir avant de toucher cette source…"
              className="w-full px-2 py-1.5 border border-stone-300 rounded text-xs"
            />
          </label>
          <label className="space-y-1 text-xs">
            <span className="block font-semibold text-stone-700">Annonces minimum attendues / run</span>
            <input
              type="number"
              min={0}
              value={expectedMin}
              onChange={e => setExpectedMin(e.target.value)}
              onBlur={saveNotesAndExpected}
              placeholder="ex: 3"
              className="w-full px-2 py-1.5 border border-stone-300 rounded text-xs"
            />
            <span className="block text-[10px] text-stone-500">
              Si un run réussi trouve moins que ça, on déclenche un avertissement de drift.
            </span>
          </label>
        </div>

        {/* Fix history */}
        <div className="mt-4">
          {(() => {
            const openDiagnostic = fixHistory.find(f => f.kind === 'high_error_rate' && (f.status === 'open' || !f.status))
            const openSuggestion = fixHistory.find(f => f.kind === 'ai_suggestion' && (f.status === 'open' || !f.status))
            return (
              <div className="flex items-center justify-between mb-2">
                <h3 className="text-xs font-bold text-stone-800">Historique &amp; auto-diagnostic</h3>
                {openDiagnostic && !openSuggestion && (
                  <button
                    onClick={requestAISuggestion}
                    disabled={aiBusy}
                    className="px-2 py-1 rounded text-[11px] font-bold bg-purple-100 hover:bg-purple-200 text-purple-800 disabled:opacity-50"
                  >
                    {aiBusy ? '⌛ Analyse…' : '✨ Demander suggestion IA'}
                  </button>
                )}
              </div>
            )
          })()}
          {aiMsg && <div className="mb-2 text-[11px] text-stone-700">{aiMsg}</div>}
          <div className="flex gap-2 mb-3">
            <input
              type="text"
              value={newFixNote}
              onChange={e => setNewFixNote(e.target.value)}
              placeholder="Note manuelle: ex. sélecteur changé de .job-card à .position-row"
              className="flex-1 px-2 py-1.5 border border-stone-300 rounded text-xs"
              onKeyDown={e => { if (e.key === 'Enter' && newFixNote.trim()) addFixNote() }}
            />
            <button
              onClick={addFixNote}
              disabled={addingFix || !newFixNote.trim() || savingProfile}
              className="px-3 py-1.5 rounded text-xs font-bold bg-stone-900 hover:bg-stone-800 text-white disabled:opacity-50"
            >
              + Ajouter
            </button>
          </div>
          {fixHistory.length === 0 ? (
            <p className="text-[11px] text-stone-500 italic">Aucun fix enregistré pour cette source.</p>
          ) : (
            <ul className="space-y-2">
              {fixHistory.slice().reverse().map((f, revIdx) => {
                // Indices in DB are oldest-first; we render newest-first, so map back.
                const i = fixHistory.length - 1 - revIdx
                const isDiagnostic = f.kind === 'high_error_rate'
                const isSuggestion = f.kind === 'ai_suggestion'
                const isOpen = f.status === 'open' || !f.status
                const dateLabel = f.date ? f.date.slice(0, 10) : '—'
                const statusBadge = f.status && f.status !== 'open' ? (
                  <span className={`text-[10px] px-1 py-0.5 rounded font-semibold ${
                    f.status === 'applied' ? 'bg-green-100 text-green-700' : 'bg-stone-200 text-stone-600'
                  }`}>{f.status === 'applied' ? 'appliqué' : 'rejeté'}</span>
                ) : null

                if (isDiagnostic) {
                  return (
                    <li key={i} className={`text-xs border-l-2 pl-2 py-1 ${isOpen ? 'border-amber-500 bg-amber-50' : 'border-stone-300'}`}>
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-stone-500 text-[10px]">{dateLabel}</span>
                        <span className="text-[10px] font-bold text-amber-700 uppercase">⚠ Auto-diagnostic</span>
                        {statusBadge}
                      </div>
                      <div className="text-stone-800 mt-0.5">
                        Taux d'erreur élevé: <strong>{f.errorsCount}/{f.attemptedCount}</strong> ({Math.round((f.errorRate ?? 0) * 100)}%)
                      </div>
                      {f.sampleFailures && f.sampleFailures.length > 0 && (
                        <details className="mt-1">
                          <summary className="text-[10px] text-stone-500 cursor-pointer hover:text-stone-700">
                            URLs échouées (échantillon)
                          </summary>
                          <ul className="mt-1 ml-2 space-y-0.5">
                            {f.sampleFailures.slice(0, 5).map((sf, j) => (
                              <li key={j} className="text-[10px] text-stone-600 truncate">
                                <code className="text-stone-700">{sf.url}</code>
                              </li>
                            ))}
                          </ul>
                        </details>
                      )}
                    </li>
                  )
                }

                if (isSuggestion) {
                  const actionLabel: Record<string, string> = {
                    update_config: 'Mise à jour de config',
                    change_url: 'Changement d\'URL',
                    disable: 'Désactiver la source',
                    no_change: 'Aucun changement recommandé',
                  }
                  return (
                    <li key={i} className={`text-xs border-l-2 pl-2 py-1 ${isOpen ? 'border-purple-500 bg-purple-50' : 'border-stone-300'}`}>
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-mono text-stone-500 text-[10px]">{dateLabel}</span>
                        <span className="text-[10px] font-bold text-purple-700 uppercase">✨ Suggestion IA</span>
                        {f.confidence && (
                          <span className="text-[10px] text-stone-500">confiance: {f.confidence}</span>
                        )}
                        {statusBadge}
                      </div>
                      <div className="text-stone-800 mt-1"><strong>Diagnostic:</strong> {f.diagnosis}</div>
                      <div className="text-stone-700 mt-1">
                        <strong>Action proposée:</strong> {actionLabel[f.proposedAction || ''] || f.proposedAction}
                      </div>
                      {f.proposedConfig && (
                        <pre className="mt-1 p-1.5 bg-stone-100 rounded text-[10px] overflow-x-auto">
{JSON.stringify(f.proposedConfig, null, 2)}
                        </pre>
                      )}
                      {f.proposedUrl && (
                        <div className="mt-1 text-[10px] text-stone-700">
                          → <code>{f.proposedUrl}</code>
                        </div>
                      )}
                      {f.reasoning && (
                        <div className="text-[11px] text-stone-600 italic mt-1">{f.reasoning}</div>
                      )}
                      {isOpen && (
                        <div className="flex gap-2 mt-2">
                          <button
                            onClick={() => fixHistoryAction(i, 'apply')}
                            disabled={aiBusy}
                            className="px-2 py-0.5 rounded text-[11px] font-bold bg-green-600 hover:bg-green-700 text-white disabled:opacity-50"
                          >
                            ✓ Appliquer
                          </button>
                          <button
                            onClick={() => fixHistoryAction(i, 'dismiss')}
                            disabled={aiBusy}
                            className="px-2 py-0.5 rounded text-[11px] font-bold bg-stone-200 hover:bg-stone-300 text-stone-700 disabled:opacity-50"
                          >
                            ✗ Rejeter
                          </button>
                        </div>
                      )}
                      {!isOpen && f.reviewedBy && (
                        <div className="text-[10px] text-stone-500 mt-1">
                          {f.status === 'applied' ? 'Appliqué' : 'Rejeté'} par {f.reviewedBy} • {fmtDate(f.reviewedAt)}
                        </div>
                      )}
                    </li>
                  )
                }

                // Legacy manual note
                return (
                  <li key={i} className="text-xs border-l-2 border-stone-300 pl-2 py-0.5">
                    <span className="font-mono text-stone-500 text-[10px]">{dateLabel}</span>
                    {f.author && <span className="text-stone-400 text-[10px] ml-1">— {f.author}</span>}
                    <div className="text-stone-800">{f.note}</div>
                  </li>
                )
              })}
            </ul>
          )}
        </div>
      </div>

      {/* Source created info */}
      <div className="text-[11px] text-stone-400">
        Source créée: {fmtDate(source.createdAt)}
        {source.lastRunAt && <> • Dernier run: {fmtDate(source.lastRunAt)}</>}
      </div>
    </div>
  )
}

function StatCard({ label, value, className }: { label: string; value: string | number; className?: string }) {
  return (
    <div className="p-3 bg-white border border-stone-200 rounded-lg">
      <div className="text-[11px] text-stone-500 mb-0.5">{label}</div>
      <div className={`text-xl font-extrabold tabular-nums ${className || 'text-stone-900'}`}>{value}</div>
    </div>
  )
}
